language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - "npm install npm@^2"
  - "npm install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "npm prune"
script:
  - "npm run test"
after_success:
  - "npm run coverage:codecov"
  - "npm run coverage:coveralls"
  - "npm run coverage:codacy"
  - "npm run build"
deploy:
  provider: releases
  api-key: $GH_TOKEN
  file:
    - "dist/formly-material.js"
    - "dist/formly-material.min.js"
    - "dist/formly-material.min.map"
  skip_cleanup: true
  on:
    tags: true